//
//  ArticleDescriptionModel.swift
//  EastLondonGuide
//
//  Created by Sean Williams on 06/10/2019.
//  Copyright © 2019 Sean Williams. All rights reserved.
//

import Foundation

enum BestRoastsInEastLondon: String {
    case Smokestak = "Erm, I'm from up north. Though there is a bit more of a story. Back when I was younger, I'd go out for on a Friday night with my friends and the next thing I know, it'd be Sunday afternoon and all I would have consumed was alcohol and small bags of salt. There would be a realisation amongst myself and whoever still had more sanity than sobriety, that a roast dinner would be required. You know, to replenish all the lost vitamins from the weekend's activities. I lived in Reading back then, and sometimes we'd get a good roast dinner, other times a fairly horrific plate of uncooked anti-food. So I took it upon myself to start a blog. Given my, erm, active social life back then, I managed one review a year. Until I got old and started bashing them out regularly."
    case TheMarksman = "The George in The Strand. Or possibly Fleet Street. It isn't a place that is talked about, it isn't a trendy place. They barely use social media to promote themselves. It didn't look especially great inside. I expected a very average roast and I still keep questioning whether it really was that good, but everything really was very good. There were some real 'wow' moments, such as the parsnip mash and the amazing cauliflower and leek cheese. The roast potatoes were actually crispy, the chicken was the plumpest and juiciest chicken that I've reviewed, and it was a fairly thick gravy. I have been told that the pork belly there isn't quite up to scratch — my tip is the chicken roast. \nBlacklock is supposed to be amazing, but I'm saving that for a special occasion. Like maybe after losing my virginity. Though you have to book weeks in advance... that'll be some holding out if I do find someone desperate enough."
    case LordMorpeth = "When are you going to stop peddling your left-wing fake-news media? It isn't £20. Well, not where I eat anyway, and I think you'd agree that I eat in a wide range of venues. At the time of writing, my average roast dinner price is just short of £16. \nI feel that you are right on picking up on a significant price increase recently. Once I've been doing this for a year or so more (which will probably happen unless I get shot or girlfriended) then I should have some good statistics in terms of average prices. \nAs to why the price has risen, I suspect that this is down to a number of business costs having risen significantly. Firstly many businesses are facing increasing rents and business rates, particularly in central London. Also staffing costs have risen due to the increased minimum wage in London (bloody Tories and their higher minimum wage). Unemployment is very low so employees are harder to find — and retain, again putting upwards pressure on staffing costs. Finally, there was a totally coincidental fall in sterling on 24 June 2016 from some unknown event that has caused much higher import costs — though on the bright side, some of Nigel Farage's hedge fund buddies made a fair few quid (allegedly)."
}

enum OurFavouriteBreakfastsInEastLondon: String {
    case Bistrotheque = "Guess what? There’s eggs on the menu at Eggbreak. And when we say eggs, we don’t just mean the ‘done any way’ kind. We mean done every way: ways that you didn’t even know were possible. Try the Crab Cake Benedict with Sriracha hollandaise if you’re after something different and downright delicious, or opt for their Sweet Potato Rosti with goat’s cheese, honey, kale, pine nuts, dill yoghurt and poached egg. It really is an eggcellent place to start the day."
    case RustyBike = "No breakfast round-up is complete without a mention of Rusty Bike and their baked eggs with tomato pepper ragout, greek yoghurt, toast and merguez sausage. It’s easily one of our favourite places for early morning feasting. If you haven’t been here yet, you seriously need to ask yourself what you’ve been doing with your Sunday mornings."
    case NTs = "Head to NTs over the weekend for their signature Breakfast in Bread. They hollow out an artisan sourdough loaf and fill the void with all your favourite breakfast foods: opt for the Original with smokey bacon, sausage, tomato, leek, mushroom, spinach, egg and cheese; the Smoked Salmon with spinach, leek, salmon, crème fraiche, egg and cheese; or the Hot Stuff with chorizo, spicy beans, red peppers, chilli mushrooms, spinach, egg and cheese. There are also some delicious options for vegans and vegetarians. Pair one of these with a Bloody Mary or a freshly squeezed juice and you’ve got yourself a true breakfast of champions."
}


enum EastLondonBreweriesAndTaprooms: String {
    case BeerMerchantsTap = "Wet behind the ears on the London scene, Beer Merchants is nonetheless another beer mile gem. The revered Manc brewery has actually been touted as the second best in the word, and has now set up shop in a bright, gallery-like space underneath an arch in Bermondsey (you'll be seeing plenty of arches in this article). It's the perfect setting for their sunny brews: think juicy IPAs, pale ales and — when you're ready for them — DIPAs. While international craft brands like Goose Island and Mikeller have scooched in on the London taproom action, for us, Cloudwater pips the competition. The best non-London beer taproom in London."
    case HowlingHops = "Beer hall-style benches, rocket-sized tanks of beer and three-quarter-pint serves define Howling Hops — the UK's first 'tank bar'. Poured pretty much fresh from the brewing process, these beers are cold, fresh and fizzy. Start on a Tropical Deluxe, and continue the journey with kolsches, pale ales and red ales. Depending on the season, you might have the option of a nice sour or stout. Street food, homemade cakes and DJs playing extremely respectable music will keep you there for a while."
    case EastLondonLiquor = "Slowly but surely, East London Liquor have cemented themselves as London's kings of sour beer. Just eyeing up their range (e.g. gooseberry & elderflower; winter berry; melon & rose, Manhattan (as in the cocktail)) is enough to make your mouth pucker. If you're a sour-phobe, fret not — their Peckham Rye taproom is flush with IPAs, stouts and lagers, year round. There's always a cider or two on, plus the fridge heaves with more cans and bottles than you could possibly get through in a session. A shaded beer garden, and pork-and-haggis-heaving buns from Slow Ritchie's, seal the deal."
}


enum BestPizzaInEastLondon: String {
    case ElGanso = "The team behind this bustling neighbourhood pizzeria use traditional Caputo flour imported directly from Naples and ferment their dough for over 24 hours before it goes in the oven. The extra air inside means that the bases puff up quickly, making them lighter and airier. The pizzas are all named after famous Italians – try the Giuseppe Garibaldi made with smoked mozzarella, Napolitan pork sausages, mushrooms and truffle oil."
    case Crate = "No two items could be more perfectly suited to each other than beer and pizza – and few places are as geared up for the pair of them as Crate is. As well as making its own beer on-site it serves crispy, thin-base pizzas that are worthy of much more than just soaking up your drinks. Try the Middle Eastern lamb variety, topped with spicy mince, alongside more traditional numbers."
    case Smokestak = "Jason Atherton's Italian restaurant serves an interesting selection of pizzas, of which half are 'bianco' meaning no tomato sauce. The toppings are the clever and creative rather than traditional - as might be expected from a Michelin-starred chef - but there's nothing overly fussy going on. Try one topped with speck, nduja, spinach, anchovy and harissa for a flavour bomb, and also look out for the monthly-changing specials designed by top chefs. What makes them worthy of inclusion is that just as much care has gone into their salty, pleasingly chewy sourdough bases as it has in choosing the toppings."
}
